version: '3.9'

services:
  go-app:
    container_name: go-app
    build: .
    environment:
      DATABASE_URL: "postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable"
    ports:
      - "8080:8080"
    networks:
      - postgres
    depends_on:
      - go_db
  go_db:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
networks:
  postgres:
    driver: bridge
